/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "mpaxos.pb-c.h"
void   mpaxos__processid_t__init
                     (Mpaxos__ProcessidT         *message)
{
  static Mpaxos__ProcessidT init_value = MPAXOS__PROCESSID_T__INIT;
  *message = init_value;
}
size_t mpaxos__processid_t__get_packed_size
                     (const Mpaxos__ProcessidT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__processid_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__processid_t__pack
                     (const Mpaxos__ProcessidT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__processid_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__processid_t__pack_to_buffer
                     (const Mpaxos__ProcessidT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__processid_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__ProcessidT *
       mpaxos__processid_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__ProcessidT *)
     protobuf_c_message_unpack (&mpaxos__processid_t__descriptor,
                                allocator, len, data);
}
void   mpaxos__processid_t__free_unpacked
                     (Mpaxos__ProcessidT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__processid_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__instid_t__init
                     (Mpaxos__InstidT         *message)
{
  static Mpaxos__InstidT init_value = MPAXOS__INSTID_T__INIT;
  *message = init_value;
}
size_t mpaxos__instid_t__get_packed_size
                     (const Mpaxos__InstidT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__instid_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__instid_t__pack
                     (const Mpaxos__InstidT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__instid_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__instid_t__pack_to_buffer
                     (const Mpaxos__InstidT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__instid_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__InstidT *
       mpaxos__instid_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__InstidT *)
     protobuf_c_message_unpack (&mpaxos__instid_t__descriptor,
                                allocator, len, data);
}
void   mpaxos__instid_t__free_unpacked
                     (Mpaxos__InstidT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__instid_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__roundid_t__init
                     (Mpaxos__RoundidT         *message)
{
  static Mpaxos__RoundidT init_value = MPAXOS__ROUNDID_T__INIT;
  *message = init_value;
}
size_t mpaxos__roundid_t__get_packed_size
                     (const Mpaxos__RoundidT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__roundid_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__roundid_t__pack
                     (const Mpaxos__RoundidT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__roundid_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__roundid_t__pack_to_buffer
                     (const Mpaxos__RoundidT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__roundid_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__RoundidT *
       mpaxos__roundid_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__RoundidT *)
     protobuf_c_message_unpack (&mpaxos__roundid_t__descriptor,
                                allocator, len, data);
}
void   mpaxos__roundid_t__free_unpacked
                     (Mpaxos__RoundidT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__roundid_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_header__init
                     (Mpaxos__MsgHeader         *message)
{
  static Mpaxos__MsgHeader init_value = MPAXOS__MSG_HEADER__INIT;
  *message = init_value;
}
size_t mpaxos__msg_header__get_packed_size
                     (const Mpaxos__MsgHeader *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_header__pack
                     (const Mpaxos__MsgHeader *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_header__pack_to_buffer
                     (const Mpaxos__MsgHeader *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgHeader *
       mpaxos__msg_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgHeader *)
     protobuf_c_message_unpack (&mpaxos__msg_header__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_header__free_unpacked
                     (Mpaxos__MsgHeader *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__proposal__init
                     (Mpaxos__Proposal         *message)
{
  static Mpaxos__Proposal init_value = MPAXOS__PROPOSAL__INIT;
  *message = init_value;
}
size_t mpaxos__proposal__get_packed_size
                     (const Mpaxos__Proposal *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__proposal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__proposal__pack
                     (const Mpaxos__Proposal *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__proposal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__proposal__pack_to_buffer
                     (const Mpaxos__Proposal *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__proposal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__Proposal *
       mpaxos__proposal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__Proposal *)
     protobuf_c_message_unpack (&mpaxos__proposal__descriptor,
                                allocator, len, data);
}
void   mpaxos__proposal__free_unpacked
                     (Mpaxos__Proposal *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__proposal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__response_t__init
                     (Mpaxos__ResponseT         *message)
{
  static Mpaxos__ResponseT init_value = MPAXOS__RESPONSE_T__INIT;
  *message = init_value;
}
size_t mpaxos__response_t__get_packed_size
                     (const Mpaxos__ResponseT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__response_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__response_t__pack
                     (const Mpaxos__ResponseT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__response_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__response_t__pack_to_buffer
                     (const Mpaxos__ResponseT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__response_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__ResponseT *
       mpaxos__response_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__ResponseT *)
     protobuf_c_message_unpack (&mpaxos__response_t__descriptor,
                                allocator, len, data);
}
void   mpaxos__response_t__free_unpacked
                     (Mpaxos__ResponseT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__response_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_common__init
                     (Mpaxos__MsgCommon         *message)
{
  static Mpaxos__MsgCommon init_value = MPAXOS__MSG_COMMON__INIT;
  *message = init_value;
}
size_t mpaxos__msg_common__get_packed_size
                     (const Mpaxos__MsgCommon *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_common__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_common__pack
                     (const Mpaxos__MsgCommon *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_common__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_common__pack_to_buffer
                     (const Mpaxos__MsgCommon *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_common__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgCommon *
       mpaxos__msg_common__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgCommon *)
     protobuf_c_message_unpack (&mpaxos__msg_common__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_common__free_unpacked
                     (Mpaxos__MsgCommon *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_common__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_prepare__init
                     (Mpaxos__MsgPrepare         *message)
{
  static Mpaxos__MsgPrepare init_value = MPAXOS__MSG_PREPARE__INIT;
  *message = init_value;
}
size_t mpaxos__msg_prepare__get_packed_size
                     (const Mpaxos__MsgPrepare *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_prepare__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_prepare__pack
                     (const Mpaxos__MsgPrepare *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_prepare__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_prepare__pack_to_buffer
                     (const Mpaxos__MsgPrepare *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_prepare__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgPrepare *
       mpaxos__msg_prepare__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgPrepare *)
     protobuf_c_message_unpack (&mpaxos__msg_prepare__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_prepare__free_unpacked
                     (Mpaxos__MsgPrepare *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_prepare__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_promise__init
                     (Mpaxos__MsgPromise         *message)
{
  static Mpaxos__MsgPromise init_value = MPAXOS__MSG_PROMISE__INIT;
  *message = init_value;
}
size_t mpaxos__msg_promise__get_packed_size
                     (const Mpaxos__MsgPromise *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_promise__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_promise__pack
                     (const Mpaxos__MsgPromise *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_promise__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_promise__pack_to_buffer
                     (const Mpaxos__MsgPromise *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_promise__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgPromise *
       mpaxos__msg_promise__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgPromise *)
     protobuf_c_message_unpack (&mpaxos__msg_promise__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_promise__free_unpacked
                     (Mpaxos__MsgPromise *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_promise__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_accept__init
                     (Mpaxos__MsgAccept         *message)
{
  static Mpaxos__MsgAccept init_value = MPAXOS__MSG_ACCEPT__INIT;
  *message = init_value;
}
size_t mpaxos__msg_accept__get_packed_size
                     (const Mpaxos__MsgAccept *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accept__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_accept__pack
                     (const Mpaxos__MsgAccept *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accept__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_accept__pack_to_buffer
                     (const Mpaxos__MsgAccept *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accept__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgAccept *
       mpaxos__msg_accept__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgAccept *)
     protobuf_c_message_unpack (&mpaxos__msg_accept__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_accept__free_unpacked
                     (Mpaxos__MsgAccept *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accept__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_accepted__init
                     (Mpaxos__MsgAccepted         *message)
{
  static Mpaxos__MsgAccepted init_value = MPAXOS__MSG_ACCEPTED__INIT;
  *message = init_value;
}
size_t mpaxos__msg_accepted__get_packed_size
                     (const Mpaxos__MsgAccepted *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accepted__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_accepted__pack
                     (const Mpaxos__MsgAccepted *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accepted__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_accepted__pack_to_buffer
                     (const Mpaxos__MsgAccepted *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accepted__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgAccepted *
       mpaxos__msg_accepted__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgAccepted *)
     protobuf_c_message_unpack (&mpaxos__msg_accepted__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_accepted__free_unpacked
                     (Mpaxos__MsgAccepted *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_accepted__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_learn__init
                     (Mpaxos__MsgLearn         *message)
{
  static Mpaxos__MsgLearn init_value = MPAXOS__MSG_LEARN__INIT;
  *message = init_value;
}
size_t mpaxos__msg_learn__get_packed_size
                     (const Mpaxos__MsgLearn *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_learn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_learn__pack
                     (const Mpaxos__MsgLearn *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_learn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_learn__pack_to_buffer
                     (const Mpaxos__MsgLearn *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_learn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgLearn *
       mpaxos__msg_learn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgLearn *)
     protobuf_c_message_unpack (&mpaxos__msg_learn__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_learn__free_unpacked
                     (Mpaxos__MsgLearn *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_learn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_decide__init
                     (Mpaxos__MsgDecide         *message)
{
  static Mpaxos__MsgDecide init_value = MPAXOS__MSG_DECIDE__INIT;
  *message = init_value;
}
size_t mpaxos__msg_decide__get_packed_size
                     (const Mpaxos__MsgDecide *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_decide__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_decide__pack
                     (const Mpaxos__MsgDecide *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_decide__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_decide__pack_to_buffer
                     (const Mpaxos__MsgDecide *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_decide__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgDecide *
       mpaxos__msg_decide__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgDecide *)
     protobuf_c_message_unpack (&mpaxos__msg_decide__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_decide__free_unpacked
                     (Mpaxos__MsgDecide *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_decide__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mpaxos__msg_slot__init
                     (Mpaxos__MsgSlot         *message)
{
  static Mpaxos__MsgSlot init_value = MPAXOS__MSG_SLOT__INIT;
  *message = init_value;
}
size_t mpaxos__msg_slot__get_packed_size
                     (const Mpaxos__MsgSlot *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_slot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mpaxos__msg_slot__pack
                     (const Mpaxos__MsgSlot *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_slot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mpaxos__msg_slot__pack_to_buffer
                     (const Mpaxos__MsgSlot *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_slot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mpaxos__MsgSlot *
       mpaxos__msg_slot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mpaxos__MsgSlot *)
     protobuf_c_message_unpack (&mpaxos__msg_slot__descriptor,
                                allocator, len, data);
}
void   mpaxos__msg_slot__free_unpacked
                     (Mpaxos__MsgSlot *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mpaxos__msg_slot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mpaxos__processid_t__field_descriptors[2] =
{
  {
    "gid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__ProcessidT, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__ProcessidT, nid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__processid_t__field_indices_by_name[] = {
  0,   /* field[0] = gid */
  1,   /* field[1] = nid */
};
static const ProtobufCIntRange mpaxos__processid_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__processid_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.processid_t",
  "ProcessidT",
  "Mpaxos__ProcessidT",
  "mpaxos",
  sizeof(Mpaxos__ProcessidT),
  2,
  mpaxos__processid_t__field_descriptors,
  mpaxos__processid_t__field_indices_by_name,
  1,  mpaxos__processid_t__number_ranges,
  (ProtobufCMessageInit) mpaxos__processid_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__instid_t__field_descriptors[2] =
{
  {
    "gid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__InstidT, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__InstidT, sid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__instid_t__field_indices_by_name[] = {
  0,   /* field[0] = gid */
  1,   /* field[1] = sid */
};
static const ProtobufCIntRange mpaxos__instid_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__instid_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.instid_t",
  "InstidT",
  "Mpaxos__InstidT",
  "mpaxos",
  sizeof(Mpaxos__InstidT),
  2,
  mpaxos__instid_t__field_descriptors,
  mpaxos__instid_t__field_indices_by_name,
  1,  mpaxos__instid_t__number_ranges,
  (ProtobufCMessageInit) mpaxos__instid_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__roundid_t__field_descriptors[3] =
{
  {
    "gid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__RoundidT, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__RoundidT, sid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__RoundidT, bid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__roundid_t__field_indices_by_name[] = {
  2,   /* field[2] = bid */
  0,   /* field[0] = gid */
  1,   /* field[1] = sid */
};
static const ProtobufCIntRange mpaxos__roundid_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mpaxos__roundid_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.roundid_t",
  "RoundidT",
  "Mpaxos__RoundidT",
  "mpaxos",
  sizeof(Mpaxos__RoundidT),
  3,
  mpaxos__roundid_t__field_descriptors,
  mpaxos__roundid_t__field_indices_by_name,
  1,  mpaxos__roundid_t__number_ranges,
  (ProtobufCMessageInit) mpaxos__roundid_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue mpaxos__msg_header__msgtype_t__enum_values_by_number[7] =
{
  { "PREPARE", "MPAXOS__MSG_HEADER__MSGTYPE_T__PREPARE", 0 },
  { "PROMISE", "MPAXOS__MSG_HEADER__MSGTYPE_T__PROMISE", 1 },
  { "ACCEPT", "MPAXOS__MSG_HEADER__MSGTYPE_T__ACCEPT", 2 },
  { "ACCEPTED", "MPAXOS__MSG_HEADER__MSGTYPE_T__ACCEPTED", 3 },
  { "LEARN", "MPAXOS__MSG_HEADER__MSGTYPE_T__LEARN", 4 },
  { "DECIDE", "MPAXOS__MSG_HEADER__MSGTYPE_T__DECIDE", 5 },
  { "SLOT", "MPAXOS__MSG_HEADER__MSGTYPE_T__SLOT", 6 },
};
static const ProtobufCIntRange mpaxos__msg_header__msgtype_t__value_ranges[] = {
{0, 0},{0, 7}
};
const ProtobufCEnumValueIndex mpaxos__msg_header__msgtype_t__enum_values_by_name[7] =
{
  { "ACCEPT", 2 },
  { "ACCEPTED", 3 },
  { "DECIDE", 5 },
  { "LEARN", 4 },
  { "PREPARE", 0 },
  { "PROMISE", 1 },
  { "SLOT", 6 },
};
const ProtobufCEnumDescriptor mpaxos__msg_header__msgtype_t__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "mpaxos.msg_header.msgtype_t",
  "msgtype_t",
  "Mpaxos__MsgHeader__MsgtypeT",
  "mpaxos",
  7,
  mpaxos__msg_header__msgtype_t__enum_values_by_number,
  7,
  mpaxos__msg_header__msgtype_t__enum_values_by_name,
  1,
  mpaxos__msg_header__msgtype_t__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_header__field_descriptors[2] =
{
  {
    "t",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgHeader, t),
    &mpaxos__msg_header__msgtype_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgHeader, pid),
    &mpaxos__processid_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_header__field_indices_by_name[] = {
  1,   /* field[1] = pid */
  0,   /* field[0] = t */
};
static const ProtobufCIntRange mpaxos__msg_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__msg_header__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_header",
  "MsgHeader",
  "Mpaxos__MsgHeader",
  "mpaxos",
  sizeof(Mpaxos__MsgHeader),
  2,
  mpaxos__msg_header__field_descriptors,
  mpaxos__msg_header__field_indices_by_name,
  1,  mpaxos__msg_header__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__proposal__field_descriptors[2] =
{
  {
    "rids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Mpaxos__Proposal, n_rids),
    PROTOBUF_C_OFFSETOF(Mpaxos__Proposal, rids),
    &mpaxos__roundid_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__Proposal, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__proposal__field_indices_by_name[] = {
  0,   /* field[0] = rids */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange mpaxos__proposal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__proposal__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.proposal",
  "Proposal",
  "Mpaxos__Proposal",
  "mpaxos",
  sizeof(Mpaxos__Proposal),
  2,
  mpaxos__proposal__field_descriptors,
  mpaxos__proposal__field_indices_by_name,
  1,  mpaxos__proposal__number_ranges,
  (ProtobufCMessageInit) mpaxos__proposal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__response_t__field_descriptors[3] =
{
  {
    "rid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__ResponseT, rid),
    &mpaxos__roundid_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__ResponseT, ack),
    &mpaxos__ack_enum__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "props",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Mpaxos__ResponseT, n_props),
    PROTOBUF_C_OFFSETOF(Mpaxos__ResponseT, props),
    &mpaxos__proposal__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__response_t__field_indices_by_name[] = {
  1,   /* field[1] = ack */
  2,   /* field[2] = props */
  0,   /* field[0] = rid */
};
static const ProtobufCIntRange mpaxos__response_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mpaxos__response_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.response_t",
  "ResponseT",
  "Mpaxos__ResponseT",
  "mpaxos",
  sizeof(Mpaxos__ResponseT),
  3,
  mpaxos__response_t__field_descriptors,
  mpaxos__response_t__field_indices_by_name,
  1,  mpaxos__response_t__number_ranges,
  (ProtobufCMessageInit) mpaxos__response_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_common__field_descriptors[1] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgCommon, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_common__field_indices_by_name[] = {
  0,   /* field[0] = h */
};
static const ProtobufCIntRange mpaxos__msg_common__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mpaxos__msg_common__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_common",
  "MsgCommon",
  "Mpaxos__MsgCommon",
  "mpaxos",
  sizeof(Mpaxos__MsgCommon),
  1,
  mpaxos__msg_common__field_descriptors,
  mpaxos__msg_common__field_indices_by_name,
  1,  mpaxos__msg_common__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_common__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_prepare__field_descriptors[2] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgPrepare, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgPrepare, n_rids),
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgPrepare, rids),
    &mpaxos__roundid_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_prepare__field_indices_by_name[] = {
  0,   /* field[0] = h */
  1,   /* field[1] = rids */
};
static const ProtobufCIntRange mpaxos__msg_prepare__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__msg_prepare__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_prepare",
  "MsgPrepare",
  "Mpaxos__MsgPrepare",
  "mpaxos",
  sizeof(Mpaxos__MsgPrepare),
  2,
  mpaxos__msg_prepare__field_descriptors,
  mpaxos__msg_prepare__field_indices_by_name,
  1,  mpaxos__msg_prepare__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_prepare__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_promise__field_descriptors[2] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgPromise, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ress",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgPromise, n_ress),
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgPromise, ress),
    &mpaxos__response_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_promise__field_indices_by_name[] = {
  0,   /* field[0] = h */
  1,   /* field[1] = ress */
};
static const ProtobufCIntRange mpaxos__msg_promise__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__msg_promise__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_promise",
  "MsgPromise",
  "Mpaxos__MsgPromise",
  "mpaxos",
  sizeof(Mpaxos__MsgPromise),
  2,
  mpaxos__msg_promise__field_descriptors,
  mpaxos__msg_promise__field_indices_by_name,
  1,  mpaxos__msg_promise__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_promise__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_accept__field_descriptors[2] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgAccept, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prop",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgAccept, prop),
    &mpaxos__proposal__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_accept__field_indices_by_name[] = {
  0,   /* field[0] = h */
  1,   /* field[1] = prop */
};
static const ProtobufCIntRange mpaxos__msg_accept__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__msg_accept__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_accept",
  "MsgAccept",
  "Mpaxos__MsgAccept",
  "mpaxos",
  sizeof(Mpaxos__MsgAccept),
  2,
  mpaxos__msg_accept__field_descriptors,
  mpaxos__msg_accept__field_indices_by_name,
  2,  mpaxos__msg_accept__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_accept__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_accepted__field_descriptors[2] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgAccepted, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ress",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgAccepted, n_ress),
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgAccepted, ress),
    &mpaxos__response_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_accepted__field_indices_by_name[] = {
  0,   /* field[0] = h */
  1,   /* field[1] = ress */
};
static const ProtobufCIntRange mpaxos__msg_accepted__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__msg_accepted__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_accepted",
  "MsgAccepted",
  "Mpaxos__MsgAccepted",
  "mpaxos",
  sizeof(Mpaxos__MsgAccepted),
  2,
  mpaxos__msg_accepted__field_descriptors,
  mpaxos__msg_accepted__field_indices_by_name,
  1,  mpaxos__msg_accepted__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_accepted__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_learn__field_descriptors[2] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgLearn, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgLearn, n_rids),
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgLearn, rids),
    &mpaxos__roundid_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_learn__field_indices_by_name[] = {
  0,   /* field[0] = h */
  1,   /* field[1] = rids */
};
static const ProtobufCIntRange mpaxos__msg_learn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__msg_learn__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_learn",
  "MsgLearn",
  "Mpaxos__MsgLearn",
  "mpaxos",
  sizeof(Mpaxos__MsgLearn),
  2,
  mpaxos__msg_learn__field_descriptors,
  mpaxos__msg_learn__field_indices_by_name,
  1,  mpaxos__msg_learn__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_learn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_decide__field_descriptors[2] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgDecide, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prop",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgDecide, prop),
    &mpaxos__proposal__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_decide__field_indices_by_name[] = {
  0,   /* field[0] = h */
  1,   /* field[1] = prop */
};
static const ProtobufCIntRange mpaxos__msg_decide__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mpaxos__msg_decide__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_decide",
  "MsgDecide",
  "Mpaxos__MsgDecide",
  "mpaxos",
  sizeof(Mpaxos__MsgDecide),
  2,
  mpaxos__msg_decide__field_descriptors,
  mpaxos__msg_decide__field_indices_by_name,
  1,  mpaxos__msg_decide__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_decide__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mpaxos__msg_slot__field_descriptors[1] =
{
  {
    "h",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Mpaxos__MsgSlot, h),
    &mpaxos__msg_header__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mpaxos__msg_slot__field_indices_by_name[] = {
  0,   /* field[0] = h */
};
static const ProtobufCIntRange mpaxos__msg_slot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mpaxos__msg_slot__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "mpaxos.msg_slot",
  "MsgSlot",
  "Mpaxos__MsgSlot",
  "mpaxos",
  sizeof(Mpaxos__MsgSlot),
  1,
  mpaxos__msg_slot__field_descriptors,
  mpaxos__msg_slot__field_indices_by_name,
  1,  mpaxos__msg_slot__number_ranges,
  (ProtobufCMessageInit) mpaxos__msg_slot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue mpaxos__ack_enum__enum_values_by_number[2] =
{
  { "SUCCESS", "MPAXOS__ACK_ENUM__SUCCESS", 0 },
  { "ERR_BID", "MPAXOS__ACK_ENUM__ERR_BID", 1 },
};
static const ProtobufCIntRange mpaxos__ack_enum__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex mpaxos__ack_enum__enum_values_by_name[2] =
{
  { "ERR_BID", 1 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor mpaxos__ack_enum__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "mpaxos.ack_enum",
  "ack_enum",
  "Mpaxos__AckEnum",
  "mpaxos",
  2,
  mpaxos__ack_enum__enum_values_by_number,
  2,
  mpaxos__ack_enum__enum_values_by_name,
  1,
  mpaxos__ack_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
